import { Hono } from "hono";
import postgres from "postgres";
import { setCookie, getCookie, deleteCookie } from "hono/cookie";
import { runAgent, listProjectFiles, listRuns } from "./agent";

const app = new Hono();
const sql = postgres(process.env.DATABASE_URL || "", { max: 8, idle_timeout: 20 });
const PORT = Number(process.env.PORT || 3000);

async function db(){
  const statements = [
    sql`CREATE EXTENSION IF NOT EXISTS pgcrypto`,
    sql`CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW())`,
    sql`CREATE TABLE IF NOT EXISTS projects(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, idea TEXT NOT NULL, spec JSONB, status TEXT DEFAULT 'draft', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
    sql`CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL)`,
    sql`CREATE TABLE IF NOT EXISTS builds(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, status TEXT DEFAULT 'queued', platform TEXT DEFAULT 'android', logs TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
    sql`CREATE TABLE IF NOT EXISTS project_files(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, path TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(project_id,path))`,
    sql`CREATE TABLE IF NOT EXISTS agent_runs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_prompt TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running', events JSONB NOT NULL DEFAULT '[]'::jsonb, summary TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`
  ];
  for(const q of statements) await q;
}
function token(){return crypto.randomUUID()+"-"+crypto.randomUUID()}
function safeUser(u:any){return {id:u.id,name:u.name,email:u.email}}
async function currentUser(c:any){const t=getCookie(c,"paras_session");if(!t)return null;const rows=await sql`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=${t} AND s.expires_at>NOW()`;return rows[0]||null}
function titleFromIdea(idea:string){const clean=idea.replace(/\s+/g," ").trim();return (clean.match(/(?:called|named)\s+["']?([^"']+)/i)?.[1]||clean.slice(0,45)||"My App").replace(/[\r\n]/g," ").trim()||"My App"}

const page=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paras AI Agent</title><style>
*{box-sizing:border-box}body{margin:0;background:#080a0f;color:#f5f7fb;font-family:Inter,system-ui,-apple-system,sans-serif}.wrap{max-width:1280px;margin:auto;padding:18px}.top{height:64px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #222735}.brand{font-size:22px;font-weight:800}.brand span{color:#7c8cff}.muted{color:#9299aa}.row{display:flex;gap:10px;align-items:center}.btn{border:1px solid #303646;background:#171b27;color:#fff;border-radius:10px;padding:10px 15px;font-weight:700;cursor:pointer}.btn.primary{background:#6677ff;border-color:#6677ff}.btn:disabled{opacity:.55;cursor:not-allowed}.layout{display:grid;grid-template-columns:230px 1fr 310px;gap:14px;margin-top:14px}.panel{background:#0f121a;border:1px solid #242a39;border-radius:14px}.side{padding:12px;height:max-content}.nav{padding:11px 12px;color:#aab1c0;border-radius:9px;margin:4px 0}.nav.active{background:#1b2030;color:#fff}.main{min-width:0}.chat{min-height:620px;display:flex;flex-direction:column}.chatHead{padding:16px;border-bottom:1px solid #252b39;display:flex;justify-content:space-between}.messages{flex:1;padding:18px;overflow:auto}.bubble{max-width:88%;padding:13px 15px;border-radius:13px;margin:10px 0;line-height:1.5;white-space:pre-wrap}.user{background:#20263a;margin-left:auto}.agent{background:#151a25;border:1px solid #262d3c}.composer{padding:14px;border-top:1px solid #252b39}.input{width:100%;background:#0a0d13;color:#fff;border:1px solid #303746;border-radius:12px;padding:13px;outline:none;resize:vertical}.composerBottom{display:flex;justify-content:space-between;align-items:center;margin-top:9px}.status{font-size:12px;color:#7fe1a7}.files{padding:12px}.file{padding:10px;border-bottom:1px solid #202634;cursor:pointer;font-family:ui-monospace,monospace;font-size:12px}.file:hover{background:#171c28}.preview{padding:12px;border-top:1px solid #252b39;max-height:330px;overflow:auto}.code{font-family:ui-monospace,monospace;font-size:11px;white-space:pre-wrap;color:#cbd2df}.auth{max-width:430px;margin:90px auto;padding:24px}.auth input{margin:6px 0}.stat{display:inline-flex;padding:7px 10px;background:#171c28;border:1px solid #292f3e;border-radius:999px;font-size:12px}.hide{display:none}.thinking{display:inline-flex;gap:5px}.dot{width:6px;height:6px;border-radius:50%;background:#8791ff;animation:p 1s infinite}.dot:nth-child(2){animation-delay:.15s}.dot:nth-child(3){animation-delay:.3s}@keyframes p{0%,100%{opacity:.25}50%{opacity:1}}@media(max-width:1050px){.layout{grid-template-columns:190px 1fr}.right{display:none}}@media(max-width:700px){.wrap{padding:10px}.layout{grid-template-columns:1fr}.side{display:none}.chat{min-height:calc(100vh - 100px)}.top .muted{display:none}}
</style></head><body><div class="wrap">
<div id="auth" class="panel auth"><div class="brand">✦ Paras <span>AI Agent</span></div><p class="muted">Build apps by talking to your coding agent.</p><input id="name" class="input" placeholder="Name"><input id="email" class="input" placeholder="Email"><input id="pass" class="input" type="password" placeholder="Password (6+ characters)"><div class="row" style="margin-top:10px"><button class="btn primary" onclick="signup()">Create account</button><button class="btn" onclick="login()">Login</button></div><div id="authmsg"></div></div>
<div id="app" class="hide"><div class="top"><div class="brand">✦ Paras <span>AI Agent</span></div><div class="row"><span id="who" class="muted"></span><button class="btn" onclick="logout()">Logout</button></div></div>
<div class="layout"><aside class="panel side"><div class="nav active">🤖 Agent</div><div class="nav">📁 Projects</div><div class="nav">🧩 Files</div><div class="nav">⚙️ Settings</div><div style="margin-top:20px" class="muted">AGENT STATUS</div><div id="agentStatus" class="stat" style="margin-top:8px">Ready</div></aside>
<main class="panel main chat"><div class="chatHead"><div><b id="projectTitle">New project</b><div class="muted" style="font-size:12px">Autonomous coding workspace</div></div><div class="row"><span class="stat" id="fileCount">0 files</span><button class="btn" onclick="newProject()">New</button></div></div><div id="messages" class="messages"><div class="bubble agent"><b>Paras AI Agent</b><br>Tell me what you want to build. I can plan the app, create files and update them through tools.<br><br>Example: <i>Build a modern food delivery web app with login, restaurants, cart and orders.</i></div></div><div class="composer"><textarea id="prompt" class="input" rows="3" placeholder="Describe the app or change you want..."></textarea><div class="composerBottom"><span id="hint" class="muted">AI agent will work on your project</span><button id="send" class="btn primary" onclick="sendAgent()">Build with Agent ⚡</button></div></div></main>
<aside class="panel right"><div class="files"><b>Project files</b><div id="files" class="muted" style="margin-top:10px">No files yet.</div></div><div class="preview"><b id="previewTitle">File preview</b><pre id="preview" class="code muted">Select a file after the agent creates one.</pre></div><div class="files"><b>Recent agent runs</b><div id="runs" class="muted" style="margin-top:10px">No runs yet.</div></div></aside></div></div></div>
<script>
const $=id=>document.getElementById(id);let current=null,projectId=null;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function add(role,text){const d=document.createElement('div');d.className='bubble '+role;d.innerHTML=esc(text);$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
function showApp(){ $('auth').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=current.name||'' }
async function boot(){try{const d=await api('/api/auth/me');current=d.user;showApp();loadProjects()}catch{}}
async function signup(){try{const d=await api('/api/auth/signup',{method:'POST',body:JSON.stringify({name:$('name').value,email:$('email').value,password:$('pass').value})});current=d.user;showApp()}catch(e){$('authmsg').innerHTML='<div style="color:#ff7f91;margin-top:10px">'+esc(e.message)+'</div>'}}
async function login(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('pass').value})});current=d.user;showApp();loadProjects()}catch(e){$('authmsg').innerHTML='<div style="color:#ff7f91;margin-top:10px">'+esc(e.message)+'</div>'}}
async function logout(){await api('/api/auth/logout',{method:'POST'});location.reload()}
async function loadProjects(){const d=await api('/api/projects');if(d.projects[0]&&!projectId){projectId=d.projects[0].id;$('projectTitle').textContent=d.projects[0].name;await refreshFiles()} }
async function newProject(){projectId=null;$('projectTitle').textContent='New project';$('messages').innerHTML='<div class="bubble agent"><b>Paras AI Agent</b><br>Ready for a new project. What should I build?</div>';$('files').innerHTML='No files yet.';$('preview').textContent='Select a file after the agent creates one.';$('runs').innerHTML='No runs yet.';$('fileCount').textContent='0 files'}
async function sendAgent(){const p=$('prompt').value.trim();if(!p)return;if($('send').disabled)return;add('user',p);$('prompt').value='';$('send').disabled=true;$('send').textContent='Agent working…';$('agentStatus').textContent='Working';$('hint').innerHTML='<span class="thinking"><span class="dot"></span><span class="dot"></span><span class="dot"></span></span>';
try{const d=await api('/api/agent/run',{method:'POST',body:JSON.stringify({projectId,prompt:p})});projectId=d.projectId;$('projectTitle').textContent=d.project?.name||'Project';add('agent',d.result.summary||'Work completed.');await refreshFiles();await refreshRuns()}catch(e){add('agent','Error: '+e.message)}finally{$('send').disabled=false;$('send').textContent='Build with Agent ⚡';$('agentStatus').textContent='Ready';$('hint').textContent='AI agent will work on your project'}}
async function refreshFiles(){if(!projectId)return;const d=await api('/api/projects/'+projectId+'/files');$('fileCount').textContent=d.files.length+' files';if(!d.files.length){$('files').innerHTML='No files yet.';return}$('files').innerHTML=d.files.map((f,i)=>'<div class="file" onclick="openFile('+i+')">'+esc(f.path)+'</div>').join('');window._files=d.files}
function openFile(i){const f=window._files[i];$('previewTitle').textContent=f.path;$('preview').textContent=f.content}
async function refreshRuns(){if(!projectId)return;const d=await api('/api/projects/'+projectId+'/runs');$('runs').innerHTML=d.runs.length?d.runs.map(r=>'<div class="file"><b>'+esc(r.status)+'</b><br>'+esc((r.summary||r.user_prompt).slice(0,100))+'</div>').join(''):'No runs yet.'}
boot();
</script></body></html>`;

app.get('/',c=>c.html(page));
app.get('/health',async c=>{try{await db();await sql`SELECT 1`;return c.json({status:'ok',database:'connected',service:'paras-ai-agent'})}catch(e){return c.json({status:'error',database:'disconnected'},500)}});
app.post('/api/auth/signup',async c=>{await db();const {name,email,password}=await c.req.json();if(!name||!email||!password||password.length<6)return c.json({error:'Name, email and 6+ character password required'},400);const existing=await sql`SELECT id FROM users WHERE lower(email)=lower(${email})`;if(existing.length)return c.json({error:'Email already registered'},409);const hash=await Bun.password.hash(password,{algorithm:'bcrypt',cost:10});const u=(await sql`INSERT INTO users(name,email,password_hash) VALUES(${name.trim()},lower(${email.trim()}),${hash}) RETURNING id,name,email`)[0];const t=token();await sql`INSERT INTO sessions(token,user_id,expires_at) VALUES(${t},${u.id},NOW()+INTERVAL '30 days')`;setCookie(c,'paras_session',t,{httpOnly:true,secure:true,sameSite:'Lax',path:'/',maxAge:2592000});return c.json({user:safeUser(u)})});
app.post('/api/auth/login',async c=>{await db();const {email,password}=await c.req.json();const rows=await sql`SELECT * FROM users WHERE lower(email)=lower(${email||''})`;if(!rows.length||!(await Bun.password.verify(password||'',rows[0].password_hash)))return c.json({error:'Invalid email or password'},401);const u=rows[0],t=token();await sql`INSERT INTO sessions(token,user_id,expires_at) VALUES(${t},${u.id},NOW()+INTERVAL '30 days')`;setCookie(c,'paras_session',t,{httpOnly:true,secure:true,sameSite:'Lax',path:'/',maxAge:2592000});return c.json({user:safeUser(u)})});
app.post('/api/auth/logout',async c=>{const t=getCookie(c,'paras_session');if(t)await sql`DELETE FROM sessions WHERE token=${t}`;deleteCookie(c,'paras_session',{path:'/'});return c.json({ok:true})});
app.get('/api/auth/me',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);return c.json({user:safeUser(u)})});
app.get('/api/projects',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const rows=await sql`SELECT p.*, (SELECT count(*) FROM builds b WHERE b.project_id=p.id) AS builds FROM projects p WHERE p.user_id=${u.id} ORDER BY p.updated_at DESC`;return c.json({projects:rows})});
app.post('/api/agent/run',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const {projectId,prompt}=await c.req.json();if(!prompt?.trim())return c.json({error:'Prompt required'},400);let id=projectId;let project:any;if(id){const rows=await sql`SELECT * FROM projects WHERE id=${id} AND user_id=${u.id}`;if(!rows.length)return c.json({error:'Project not found'},404);project=rows[0]}else{project=(await sql`INSERT INTO projects(user_id,name,idea,spec,status) VALUES(${u.id},'New AI App',${prompt.trim()},${JSON.stringify({mode:'agent'})},'agent-running') RETURNING *`)[0];id=project.id}await sql`UPDATE projects SET idea=${prompt.trim()},status='agent-running',updated_at=NOW() WHERE id=${id} AND user_id=${u.id}`;try{const result=await runAgent(id,prompt.trim());await sql`UPDATE projects SET status='ready',updated_at=NOW() WHERE id=${id}`;return c.json({projectId:id,project:{id,name:project.name},result})}catch(e:any){await sql`UPDATE projects SET status='error',updated_at=NOW() WHERE id=${id}`;return c.json({error:e.message||'Agent failed',projectId:id},500)}});
app.get('/api/projects/:id/files',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const rows=await sql`SELECT p.id FROM projects p WHERE p.id=${c.req.param('id')} AND p.user_id=${u.id}`;if(!rows.length)return c.json({error:'Project not found'},404);return c.json({files:await listProjectFiles(c.req.param('id'))})});
app.get('/api/projects/:id/runs',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const rows=await sql`SELECT p.id FROM projects p WHERE p.id=${c.req.param('id')} AND p.user_id=${u.id}`;if(!rows.length)return c.json({error:'Project not found'},404);return c.json({runs:await listRuns(c.req.param('id'))})});
app.get('/api/projects/:id/code',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const rows=await sql`SELECT p.id FROM projects p WHERE p.id=${c.req.param('id')} AND p.user_id=${u.id}`;if(!rows.length)return c.json({error:'Project not found'},404);return c.json({files:await listProjectFiles(c.req.param('id'))})});
app.post('/api/projects/:id/builds',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);const id=c.req.param('id');const p=await sql`SELECT id FROM projects WHERE id=${id} AND user_id=${u.id}`;if(!p.length)return c.json({error:'Project not found'},404);const b=(await sql`INSERT INTO builds(project_id,status,platform,logs) VALUES(${id},'queued','android','Build queued. Android build worker will be connected in the next deployment step.') RETURNING *`)[0];return c.json({build:b})});
app.get('/api/settings',async c=>{const u=await currentUser(c);if(!u)return c.json({error:'Not logged in'},401);return c.json({user:safeUser(u),aiConfigured:Boolean(process.env.OPENAI_API_KEY),model:process.env.OPENAI_MODEL||'gpt-5.6-luna',githubConfigured:Boolean(process.env.GITHUB_TOKEN),buildConfigured:true})});

db().catch(e=>{console.error(e);process.exit(1)});
Bun.serve({port:PORT,fetch:app.fetch});
